### ISSUE TITLE
Postman collection V2.1

### ISSUE THREAD

**Issue by hendrasyp** [p8ul/postman2apiary#2]
When using Postman Collection v2.1 error 
``` * Generating api markup
Traceback (most recent call last):
  File "run.py", line 35, in <module>
    main()
  File "run.py", line 28, in main
    app = PostmanToApiary(data)
  File "path\converter.py", line 22, in __init__
    self.get_data()
  File "path\converter.py", line 33, in get_data
    self.name = self.data['name']
KeyError: 'name'```

**Comment by asntcrz** [comment]
Same error with V2.0 and also error with V1.0:

```
 * Generating api markup
Traceback (most recent call last):
  File "run.py", line 35, in <module>
    main()
  File "run.py", line 29, in main
    app.write()
  File "/xxx/postman2apiary/app/converter.py", line 43, in write
    doc.write(self.description)
TypeError: write() argument must be str, not None
```

**Comment by p8ul** [comment]
Thank you for the feedback. I have [fixed the issue](https://github.com/p8ul/postman2apiary/commit/ee8ab0ce15bf54d0317d9e280e020995d4723d32), but you should consider 

`Editing your postman collection requests with relevant names and description. Import postman_collection.json from postman2apiary/app/ directory for a quick demo on how to name and describe your requests. Expected output should be something like Polls API documentation`

To get a good result with the script. Please edit your request and at least give it some `descriptions` and `name` like shown below.

<img width="1282" alt="screenshot 2019-01-03 at 21 54 01" src="https://user-images.githubusercontent.com/17355400/50655755-1ac8da00-0fa2-11e9-89da-2982eed05752.png">

If the error still persists, you can share your exported postman collection json file.
